server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: spring-cloud-gateway

  # Spring Cloud Gateway using property based config
  # (use these configurations or class SpringCloudConfig)
#  cloud:
#    gateway:
#      # (use this property (default-filters) or @Bean GlobalFilter globalFilter())
#      default-filters:
#        - name: CustomFilter
#      routes:
#        - id: oneModule
#          uri: lb://ONE-SERVICE
#          predicates:
#            - Path=/one/**
#          filters:
#            - CustomFilter
#            - AddRequestHeader=one-request, one-request-header
#            - AddResponseHeader=one-response, one-response-header
#        - id: twoModule
#          uri: lb://TWO-SERVICE
#          predicates:
#            - Path=/two/**
#          filters:
#            - CustomFilter
#            - AddRequestHeader=two-request, two-request-header
#            - AddResponseHeader=two-response, two-response-header