apiVersion: v1
kind: Service
metadata:
  name: postgres-instance
spec:
  selector:
    app: postgres-instance
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-instance
spec:
  selector:
    matchLabels:
      app: postgres-instance
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-instance
    spec:
      containers:
        - image: postgres
          name: postgres-container
          env:
            - name: POSTGRES_USER
              value: ${DATASOURCE_USERNAME}
            - name: POSTGRES_PASSWORD
              value: ${DATASOURCE_PASSWORD}
            - name: POSTGRES_DB
              value: sport_db
          ports:
            - containerPort: 5432
              name: postgres-inst
