apiVersion: v1
kind: Service
metadata:
  name: sport-app-reactive
spec:
  selector:
    app: sport-app-reactive
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
