apiVersion: v1
kind: Service
metadata:
  name: sport-app-reactive
  labels:
    name: sport-app-reactive
    {{- template "labels" . }}
spec:
  selector:
    app: sport-app-reactive
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  type: LoadBalancer
