server:
  port: 8080

#datasource settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentoring_recipes_db
#    Uncomment next line to run app via Docker using postgres Docker image
#    url: jdbc:postgresql://local-postgres:5432/mentoring_recipes_db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

#data settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Hibernate ddl auto (create, create-drop, validate, update)
    show-sql: false

login:
  max-failed-attempts: 3
  lock-time: 300000 # 5 minutes (5 * 60 * 1000)