server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      notification: notification_topic
    consumer:
      group-id: courier_consumers
    #      auto-offset-reset: earliest
