apiVersion: v1
kind: Service
metadata:
  name: events
  labels:
    name: events
    {{- template "labels" . }}
spec:
  selector:
    app: events
  ports:
  - name: "http"
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  type: LoadBalancer
