data:
  sport:
    url: "https://sports.api.decathlon.com/sports"

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sport_db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    url: jdbc:postgresql://localhost:5432/sport_db
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  profiles:
    active: Rest # Task

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
