server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  endpoint:
    health:
      show-details: always

#datasource settings
spring:
  datasource:
    url: jdbc:h2:file:./module-28-spring-boot/task-2/mentoring_recipes_db
    driverClassName: org.h2.Driver
#   TODO: never commit password!!!!!!! this one is only for testing purpose
    username: abc123
    password: abc123

#data settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
#    show-sql: true

#console settings
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false

#OAuth 2.0
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}